### ISSUE TITLE
test function which does not always fail (only for certain known inputs)

### ISSUE THREAD

**Issue by tdhock** [akhikolla/RcppDeepState#34]
hi @akhikolla looks like your current functions in testpkgs always fail. that is a good start but it would be even better if you could make an example that only fails for some known inputs. for example
```
int allocate_read(int index){
  int x[100];
  return x[index];
} 
```
should work fine if index is between 0 and 99, but should fail otherwise.

**Comment by akhikolla** [comment]
Write Index Out of Bound
```
int rcpp_write_index_outofbound(int wbound){
  int x = wbound;
  int *stack_array = new int[100];
  stack_array[wbound] = 50;
  return 0; 

} 
```

Read Out of Bound 

```
int rcpp_read_out_of_bound(int rbound){
  int *stack_array = new int[1000];
  return stack_array[rbound];
} 
  
```
Use after free and Use after deallocate always fail because the purpose of these functions is to clear the memory[delete/free] and try to use it. Same with zero-sized array writing to a zero-sized array fails. I can try adding a few more functions that fail only for certain inputs. Same with uninitialized value(trying to use uninitialized var always throws an error).

```
int rcpp_use_uninitialized(int u_value){
    int x;
    if(x < u_value)
    return u_value;
    else
    return x+u_value;
} 
```

**Comment by tdhock** [comment]
great is this done then?

**Comment by akhikolla** [comment]
Yes, the issue is resolved now.
